import test from 'node:test'
import assert from 'node:assert/strict'
import { xcaReportModuleUrl } from './load-api-test-module.mjs'
const { prepareXCAReportTarget, readXCAReportTarget, attachXCAReportDraft, validateXCAReportSelection, storedXCAAttachments } = await import(xcaReportModuleUrl)
function detail() { return { id:1,summary:{patientId:1626,examinationId:1210,analysisId:467,resultId:15,originalPatientId:'273'} } }
function target() { return {id:80,patientId:1626,encounterId:91,status:'DRAFT',baseVersionId:90,versionNo:1,content:{existing_section:'keep'},text:'기존 본문'} }
function attachment() { return {detail_id:1,base_version_id:90,analysis_id:467,result_id:15,examination_id:1210,source_bundle_sha256:'18ffc48b71309379598a3dc6d1b1ac4a858e567f4d6ee917532e2a08e01a3569',review_note:'검토 의견',status:'DRAFT_REQUIRES_REVIEW',frames:[{id:101,source_file_asset_id:201}],summary:{patient_id:'273',backend_context:{backend_patient_id:1626,examination_id:1210}}} }
function version() { return { id:95,medical_result:80,version_no:2,source_type:'DOCTOR_EDIT',content_json:{existing_section:'keep',xca_attachments:[attachment()]},content_text:'기존 본문\n\n검토 의견'} }
function medical(versions=[]) { return {medical_result:{id:80,patient:1626,encounter:91,examination:1210,report_type:'XCA_2D',status:'DRAFT'},versions} }
function reply(payload,status=200) {return {ok:status<400,status,json:async()=>payload}}
test('new XCA report target binds the completed result to its examination and rereads latest version',async()=>{const calls=[];globalThis.fetch=async(u,o)=>{calls.push([u,o]);return reply(calls.length===1?medical().medical_result:medical())};const t=await prepareXCAReportTarget('','STAFF',1626,1210,15);assert.equal(t.baseVersionId,null);assert.equal(t.versionNo,0);assert.equal(calls[0][0],'/api/examinations/1210/medical-results/');assert.deepEqual(JSON.parse(calls[0][1].body),{report_type:'XCA_2D',analysis_result_id:15});assert.equal(calls[1][1].method,'GET')})
test('existing report target loads highest version and preserves content',async()=>{globalThis.fetch=async()=>reply(medical([{id:90,medical_result:80,version_no:1,content_json:{section:'keep'},content_text:'본문'},{id:93,medical_result:80,version_no:3,content_json:{section:'new'},content_text:'새 본문'}]));const t=await readXCAReportTarget('','STAFF',80,1626,91);assert.equal(t.baseVersionId,93);assert.equal(t.content.section,'new')})
test('wrong patient/encounter and malformed prior content fail',async()=>{for(const kind of ['patient','encounter','content']) {const m=medical();if(kind==='patient')m.medical_result.patient=1614;if(kind==='encounter')m.medical_result.encounter=99;if(kind==='content')m.versions=[{id:90,medical_result:80,version_no:1,content_json:[],content_text:'bad'}];globalThis.fetch=async()=>reply(m);await assert.rejects(()=>readXCAReportTarget('','STAFF',80,1626,91))}})
test('blank note, duplicate/excess frames and other patient stop before network',async()=>{const invalids=[{frames:[],note:'검토'},{frames:[101,101],note:'검토'},{frames:Array.from({length:13},(_,i)=>i+1),note:'검토'},{frames:[101],note:' '},{frames:[101],note:'x'.repeat(4001)}];let calls=0;globalThis.fetch=async()=>{calls++;return reply({})};for(const invalid of invalids)await assert.rejects(()=>attachXCAReportDraft('','STAFF',detail(),target(),invalid.frames,invalid.note));assert.throws(()=>validateXCAReportSelection(detail(),{...target(),patientId:1614},[101],'검토'));assert.equal(calls,0)})
test('explicit attachment POST includes optimistic base and no signing/release calls',async()=>{const calls=[],v=version();globalThis.fetch=async(u,o)=>{calls.push([u,o]);return reply(calls.length===1?{report_version:v,attachment_id:9,reused:false}:calls.length===2?v:medical([v]))};const saved=await attachXCAReportDraft('','STAFF',detail(),target(),[101],' 검토 의견 ','REAUTH');assert.equal(saved.versionId,95);assert.equal(saved.attachmentId,9);const post=JSON.parse(calls[0][1].body);assert.deepEqual(post,{detail_id:1,frame_ids:[101],review_note:'검토 의견',base_version_id:90,reauth_token:'REAUTH'});assert.equal(calls.filter(([,o])=>o.method==='POST').length,1);assert.ok(calls.every(([u])=>!u.includes('signoff')&&!u.includes('generate-report')&&!u.includes('release')&&!u.includes('8003')));assert.equal(calls[1][0],'/api/report-versions/95/')})
test('stale base 409 and expired credentials 401 never replay the POST',async()=>{for(const status of [409,401,403]){let calls=0;globalThis.fetch=async()=>{calls++;return reply({},status)};await assert.rejects(()=>attachXCAReportDraft('','STAFF',detail(),target(),[101],'검토 의견'));assert.equal(calls,1)}})
test('wrong returned frames/patient/bundle and changed prior body/section fail readback',async()=>{for(const kind of ['frames','patient','bundle','section','body','version']) {const v=version();if(kind==='frames')v.content_json.xca_attachments[0].frames[0].id=999;if(kind==='patient')v.content_json.xca_attachments[0].summary.backend_context.backend_patient_id=1614;if(kind==='bundle')v.content_json.xca_attachments[0].source_bundle_sha256='b'.repeat(64);if(kind==='section')v.content_json.existing_section='lost';if(kind==='body')v.content_text='사라진 본문';if(kind==='version')v.version_no=7;let calls=0;globalThis.fetch=async()=>{calls++;return reply({report_version:v,attachment_id:9,reused:false})};await assert.rejects(()=>attachXCAReportDraft('','STAFF',detail(),target(),[101],'검토 의견'));assert.equal(calls,1)}})
test('persisted version mismatch blocks success without another write',async()=>{const v=version();let calls=0;globalThis.fetch=async()=>{calls++;return reply(calls===1?{report_version:v,attachment_id:9,reused:false}:{...v,content_text:'different'})};await assert.rejects(()=>attachXCAReportDraft('','STAFF',detail(),target(),[101],'검토 의견'));assert.equal(calls,2)})
test('draft state is checked after stored version readback',async()=>{const v=version();let calls=0;globalThis.fetch=async()=>{calls++;const m=medical([v]);m.medical_result.status='SIGNED';return reply(calls===1?{report_version:v,attachment_id:9,reused:false}:calls===2?v:m)};await assert.rejects(()=>attachXCAReportDraft('','STAFF',detail(),target(),[101],'검토 의견'));assert.equal(calls,3)})
test('stored attachment reload uses saved frame IDs rather than current selection',()=>{const t=target();t.content.xca_attachments=[attachment()];assert.deepEqual(storedXCAAttachments(t,detail()),[{note:'검토 의견',frameIds:[101]}]);t.content.xca_attachments[0].frames.push({id:101});assert.throws(()=>storedXCAAttachments(t,detail()))})
test('same attachment reuse is accepted after independent readback',async()=>{const v=version();let calls=0;globalThis.fetch=async()=>reply(++calls===1?{report_version:v,attachment_id:9,reused:true}:calls===2?v:medical([v]));assert.equal((await attachXCAReportDraft('','STAFF',detail(),target(),[101],'검토 의견')).reused,true);assert.equal(calls,3)})
test('missing staff auth does not create a draft',async()=>{let calls=0;globalThis.fetch=async()=>{calls++;return reply({})};await assert.rejects(()=>prepareXCAReportTarget('',null,1626,1210,15));assert.equal(calls,0)})
