import test from 'node:test'
import assert from 'node:assert/strict'
import { xcaDetailsModuleUrl } from './load-api-test-module.mjs'
const { parseXCADetail, parseXCAFrame, listXCAFrames, listXCADetails, readXCAFrame } = await import(xcaDetailsModuleUrl)
globalThis.window = { location: { origin: 'http://127.0.0.1:4173' } }
function fixture() {
  const context = { backend_patient_id:1614, source_subject_id:'241', examination_id:1198, scope:'all_classified_series_in_examination', excluded_unknown_sequence_ids:[], sequences:[{sequence_id:11,sequence_no:'1',side:'RIGHT',frame_count:2}] }
  const classification = { side:'RIGHT',features:{n_series:1,n_frames:2},threshold:.5,any_stenosis:{ai_score:.1,prediction:0},significant_stenosis:{ai_score:.2,prediction:0} }
  return { id:1,backend_patient_id:1614,examination_id:1198,status:'REVIEW_REQUIRED',detail_version:'0.1.0-demo',source_bundle_sha256:'18ffc48b71309379598a3dc6d1b1ac4a858e567f4d6ee917532e2a08e01a3569',analysis_id:466,job_id:16,result_id:14,input_snapshot:context,n_frames:2,created_at:'2026-09-17T12:00:00Z',
    summary:{backend_context:context,status:'COMPLETED',serving_scope:'VALIDATED_ANGIOCAD_DEMO_INTEGRATION',analysis_unit:'patient_side',api_version:'1.0.0-demo',patient_id:'241',fold:3,n_series:1,n_frames:2,processing_seconds:1.5,sides:[classification]},
    series:[{series_id:'1',side:'RIGHT',n_frames:2,score_scope:'single_series_exploratory',classification_validation:'NOT_VALIDATED_FOR_SERIES_CLASSIFICATION',classification,suspected_frame_indices:[1],representative_frame_index:1}] }
}
function frame(index=0) { return {id:100+index,detail_id:1,sequence_id:11,sequence_no:'1',frame_index:index,width:512,height:512,localization:{validation:'weak_localization',transform:{coordinate_space:'source_png_pixels',source_hw:[512,512]}},source:{file_asset_id:200+index,sha256:'a'.repeat(64),url:'https://objects.invalid/source.png?signature=test'},mask:index===1?{file_asset_id:300,sha256:'b'.repeat(64),url:'https://objects.invalid/mask.png?signature=test'}:null} }
test('saved detail retains original/backend IDs and exploratory per-series scores',()=>{const d=parseXCADetail(fixture(),1614,1198);assert.equal(d.id,1);assert.equal(d.summary.originalPatientId,'241');assert.equal(d.summary.resultId,14);assert.equal(d.series[0].any.aiScore,.1);assert.equal(d.series[0].representative,1)})
test('wrong patient/exam, bundle, unclassified side, validation and duplicate series fail',()=>{
  for(const kind of ['patient','exam','bundle','side','validation','duplicate']) { const v=structuredClone(fixture()); if(kind==='patient')v.backend_patient_id=1626;if(kind==='exam')v.examination_id=1210;if(kind==='bundle')v.source_bundle_sha256='b'.repeat(64);if(kind==='side')v.series[0].side='UNKNOWN';if(kind==='validation')v.series[0].classification_validation='VALIDATED';if(kind==='duplicate')v.series.push(v.series[0]);assert.throws(()=>parseXCADetail(v,1614,1198),undefined,kind) }
})
test('candidate duplicates, out-of-range and representative mismatch fail',()=>{for(const candidates of [[2],[1,1],[0,1]]) {const v=structuredClone(fixture());v.series[0].suspected_frame_indices=candidates;assert.throws(()=>parseXCADetail(v,1614,1198))}})
test('archived frame source dimensions and mask stay tied to saved detail/sequence',()=>{const d=parseXCADetail(fixture(),1614,1198);const f=parseXCAFrame(frame(1),d);assert.equal(f.index,1);assert.equal(f.width,512);assert.ok(f.maskUrl);for(const kind of ['detail','sequence','index','geometry','url']) {const v=frame(1);if(kind==='detail')v.detail_id=99;if(kind==='sequence')v.sequence_id=33;if(kind==='index')v.frame_index=9;if(kind==='geometry')v.width=256;if(kind==='url')v.source.url='http://public.invalid/image';assert.throws(()=>parseXCAFrame(v,d),undefined,kind)}})
test('saved frame pages use backend GET only and do not call local GPU',async()=>{const calls=[];globalThis.fetch=async(url,options)=>{calls.push([url,options]);const page=calls.length;return {ok:true,json:async()=>({count:2,page,next_page:page===1?2:null,frames:[frame(page-1)]})}};const result=await listXCAFrames('', 'STAFF',parseXCADetail(fixture(),1614,1198),11);assert.equal(result.length,2);assert.equal(calls.length,2);assert.ok(calls.every(([u,o])=>u.startsWith('/api/xca-details/1/frames/')&&!o.method&&o.headers.Authorization==='Bearer STAFF'));assert.ok(calls.every(([u])=>!u.includes('8002')&&!u.includes('8003')))})
test('early end, duplicated page, invalid continuation fail',async()=>{for(const kind of ['early','duplicate','next']) {let n=0;globalThis.fetch=async()=>({ok:true,json:async()=>{n++;return {count:2,page:n,next_page:kind==='early'?null:kind==='next'?7:n===1?2:null,frames:[frame(kind==='duplicate'?0:n-1)]}}});await assert.rejects(()=>listXCAFrames('','STAFF',parseXCADetail(fixture(),1614,1198),11))}})
test('history reads do not need bridge and patient/exam query is bound',async()=>{let called;globalThis.fetch=async(u,o)=>{called=[u,o];return {ok:true,json:async()=>({results:[fixture()]})}};assert.equal((await listXCADetails('','STAFF',1614,1198))[0].id,1);assert.equal(called[0],'/api/examinations/1198/xca-details/?patient_id=1614');assert.equal(called[1].cache,'no-store')})
test('missing staff auth and permission failures do not auto-retry',async()=>{let calls=0;globalThis.fetch=async()=>{calls++;return {ok:false,status:403}};await assert.rejects(()=>listXCADetails('',null,1614,1198));assert.equal(calls,0);await assert.rejects(()=>listXCADetails('','STAFF',1614,1198));assert.equal(calls,1)})
test('report evidence rereads exact saved DB frame ID with patient binding',async()=>{let path;globalThis.fetch=async(u)=>{path=u;return {ok:true,json:async()=>frame(1)}};const d=parseXCADetail(fixture(),1614,1198);assert.equal((await readXCAFrame('','STAFF',d,101)).id,101);assert.equal(path,'/api/xca-details/1/frames/101/?patient_id=1614');await assert.rejects(()=>readXCAFrame('','STAFF',d,100))})
